#!/bin/sh
MIRROR_DEBIAN="http://ftp.jp.debian.org/debian/"
MIRROR_SECURITY="http://security.debian.org/"
BOOTOPTION_LIVE="quiet locale=ja_JP.UTF-8 keyb=jp kmodel=jp106"
PACKAGES="ruby1.9.1 ruby1.9.2"
lh config noautoconfig \
       --architecture i386 \
       --binary-images iso \
       --iso-volume RubyLive \
       --distribution lenny \
       --language ja \
       --bootappend-live "${BOOTOPTION_LIVE}" \
       --mirror-bootstrap ${MIRROR_DEBIAN} \
       --mirror-chroot ${MIRROR_DEBIAN} \
       --mirror-chroot-security ${MIRROR_SECURITY} \
       --mirror-binary ${MIRROR_DEBIAN} \
       --mirror-binary-security ${MIRROR_SECURITY} \
       --packages-lists "gnome-core" \
       --packages $PACKAGES \
       --debian-installer netinst \
       --debian-installer-distribution lenny \
       --debian-installer-gui enabled \
       ${@}

