#!/bin/sh
IMAGE_PREFIX=debian_live-binary
BUILDDATE=`date +%Y%m%d%H%M%S`
lh_build noautoconfig 2>&1 | tee ${IMAGE_PREFIX}-${BUILDDATE}.buildlog
# rename files
if [ -f binary.iso ]; then
   mv binary.iso ${IMAGE_PREFIX}-${BUILDDATE}.iso
elif [ -f binary.img ]; then
   mv binary.img ${IMAGE_PREFIX}-${BUILDDATE}.img
fi
[ -f binary.list ] && mv binary.list ${IMAGE_PREFIX}-${BUILDDATE}.list
[ -f binary.packages ] && mv binary.packages ${IMAGE_PREFIX}-${BUILDDATE}.packages

